### ISSUE TITLE
[Bug] Extension fails to load due to repo name

### ISSUE THREAD

**Issue by TFWol** [xanthousm/text-gen-webui-ui_tweaks#2]
Textgen is picky with the name. The `-` will cause a syntax error.

```
ERROR:Failed to load the extension "text-gen-webui-ui_tweaks".
Traceback (most recent call last):
  File "C:\Users\user\oobabooga-windows\text-generation-webui\modules\extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1
    import extensions.text-gen-webui-ui_tweaks.script
                          ^
SyntaxError: invalid syntax
```

It'll show up in the GUI's list of extensions to choose from and even be checked, but won't actually be loaded.

I was able to get it to work by renaming the repo folder from **text-gen-webui-ui_tweaks** to **text_gen_webui_ui_tweaks** and then use `--extension text_gen_webui_ui_tweaks`

Recommend changing repo name and/or providing more detailed install instructions for other users.

btw, extension itself is very useful 👍

**Comment by xanthousm** [comment]
I've been using it with a renamed folder so I didn't notice. I'll add it to the install instructions. Thanks for letting me know!
